- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: false
      tags:
        - packages
  tasks:
    - include: tasks/packages.yml

- hosts: localhost
  remote_user: root
  become: true
  become_user: stuart
  vars:
    python3_version: 3.7.5
    python2_version: 2.7.17
  tasks:
    - include: tasks/homeshick.yml
    - include: tasks/systemd.yml
    - include: tasks/python.yml
    - include: tasks/vim.yml
