- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      name:
        - arandr
        - awesome
        - compton
        - dex
        - exuberant-ctags
        - htop
        - lightdm
        - neovim
        - oxygen-icon-theme
        - oxygencursors
        - termit
        - tmux
        - xsecurelock
        - xss-lock

- hosts: localhost
  remote_user: root
  become: true
  become_user: stuart
  tasks:
    - name: Checkout HomeSHick git
      git: repo=git://github.com/andsens/homeshick.git dest="{{ ansible_user_dir }}/.homesick/repos/homeshick"
    - name: Checkout Castles
      git: repo="git://github.com/stuartf/{{ item }}-castle.git" dest="{{ ansible_user_dir }}/.homeshick/repos/{{ item }}-castle"
      with_items:
        - awesome
        - bash
        - git
        - gtk
        - termit
        - tmux
        - vim
    - name: Link Castles
      command: "{{ ansible_user_dir }}/.homesick/repos/homeshick/bin/homeshick link -f -q"
