- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      name:
        - htop
        - tmux
        - awesome
        - dex
        - lightdm
        - arandr
        - compton
        - exuberant-ctags
        - neovim
        - oxygen-icon-theme
        - oxygencursors
        - xsecurelock
        - xss-lock
