- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
      name:
        - arandr
        - awesome
        - compton
        - dex
        - exuberant-ctags
        - htop
        - git
        - lightdm
        - neovim
        - oxygen-icon-theme
        - oxygencursors
        - termit
        - tmux
        - xsecurelock
        - xss-lock

- hosts: localhost
  remote_user: root
  become: true
  become_user: stuart
  tasks:
    - name: Checkout HomeSHick git
      git: repo=git://github.com/andsens/homeshick.git dest="{{ ansible_user_dir }}/.homesick/repos/homeshick"
    - name: Checkout Castles
      git: repo="git://github.com/stuartf/{{ item }}-castle.git" dest="{{ ansible_user_dir }}/.homeshick/repos/{{ item }}-castle"
      with_items:
        - awesome
        - bash
        - git
        - gtk
        - termit
        - tmux
        - vim
    - name: Link Castles
      command: "{{ ansible_user_dir }}/.homesick/repos/homeshick/bin/homeshick link -f -q"
    - name: Enable User Systemd Services
      systemd:
        daemon_reexec: true
        enabled: true
        scope: user
        state: started
        name: "{{ item }}"
      with_items:
        - xss-lock
        - compton
    - name: Install Vim Plugins
      command: "nvim -E -s -u {{ ansible_user_dir }}/.config/nvim/init.vim +PluginInstall +qall"
