- name: Install packages
  apt:
    name:
      - exuberant-ctags
      - htop
      - git
      - neovim
      - tmux
  tags:
    - packages

- name: Install GUI packages
  apt:
    name:
      - arandr
      - awesome
      - compton
      - dex
      - lightdm
      - oxygen-icon-theme
      - oxygencursors
      - termit
      - xsecurelock
      - xss-lock
  tags:
    - gui
    - packages
