- name: Install packages
  apt:
    name:
      - arandr
      - awesome
      - compton
      - dex
      - exuberant-ctags
      - htop
      - git
      - lightdm
      - neovim
      - oxygen-icon-theme
      - oxygencursors
      - termit
      - tmux
      - xsecurelock
      - xss-lock
