- name: Install Vim Plugins
  command: "nvim -E -s -u {{ ansible_user_dir }}/.config/nvim/init.vim +PluginInstall +qall"

- name: Build VimProc
  command:
    cmd: make
    chdir: "{{ ansible_user_dir }}/.config/nvim/bundle/vimproc.vim"

- name: Build PyEnvs for Vim
  command: "{{ ansible_user_dir }}/.pyenv/bin/pyenv virtualenv {{ item }} nvim-python-{{ item }}"
  with_items:
    - "{{ python2_version }}"
    - "{{ python3_version }}"

- name: Install python2 deps for Vim
  vars:
    pyenv_root: "{{ ansible_user_dir }}/.pyenv"
  pip:
    virtualenv: "{{ pyenv_root }}/versions/{{ python2_version }}/envs/nvim-python-{{ python2_version }}"
    name: pynvim

- name: Install python3 deps for Vim
  vars:
    pyenv_root: "{{ ansible_user_dir }}/.pyenv"
  pip:
    virtualenv: "{{ pyenv_root }}/versions/{{ python3_version }}/envs/nvim-python-{{ python3_version }}"
    name:
      - pynvim
      - slugify
      - SimpleWebSocketServer
