- name: Install Vim Plugins
  command: "nvim -E -s -u {{ ansible_user_dir }}/.config/nvim/init.vim +PluginInstall +qall"

- name: Build VimProc
  command:
    cmd: make
    chdir: "{{ ansible_user_dir }}/.config/nvim/bundle/vimproc.vim"

- name: Setup python2 PyEnv for Vim
  vars:
    pyenv_root: "{{ ansible_user_dir }}/.pyenv"
  pip:
    virtualenv: "{{ pyenv_root }}/versions/{{ python2_version }}/envs/nvim-python-{{ python2_version }}"
    virtualenv_command: "{{ pyenv_root }}/bin/pyenv virtualenv nvim-python-{{ python2_version }}"
    name: pynvim

- name: Setup python3 PyEnv for Vim
  vars:
    pyenv_root: "{{ ansible_user_dir }}/.pyenv"
  pip:
    virtualenv: "{{ pyenv_root }}/versions/{{ python3_version }}/envs/nvim-python-{{ python3_version }}"
    virtualenv_command: "{{ pyenv_root }}/bin/pyenv virtualenv nvim-python-{{ python3_version }}"
    name:
      - pynvim
      - slugify
      - SimpleWebSocketServer
